- name: Automation with terraform and ansible
  hosts: all

  tasks:
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes
       
  - name: installing nginx
    apt:
         name: nginx
         state: present

  - name: starting nginx service
    service:
         name: nginx
         state: started